# StarGate Atlantis
# Project by Alemiz
# Website: https://github.com/Alemiz112

# Supports more connections
connections:
  lobby1:
    address: 192.168.0.50
    port: 47007
    password: 123456789

# Change log level to log packets in debug mode.
# Set to 0 for no packet logs.
# Set to 1 to log packets except Ping, Pong and connection packets.
# Set to 2 to log all packets.
logLevel: 0
# Interval in ticks to receive data from connection
# Lower interval, faster packet decoding and encoding
tickInterval: 2
# Default client will be used if no clientName specified in api functions
defaultClient: "lobby1"
# Start clients after plugin is enabled.
# Disabling auto start will allow plugins to trigger connection manually.
autoStart: true